import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from './scroll.module.css'

export default function Home() {
  const [questionOne, setQuestionOne] = useState(null)
  const [questionTwo, setQuestionTwo] = useState(null)
  const [questionThree, setQuestionThree] = useState(null)
  const [questionFour, setQuestionFour] = useState(null)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div className={styles.content}>
          <div className={styles.questionOne}>
            <form action="#" method="post">
              <h1>Does your Character Use Magic?</h1>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionOne(true)
                }}
              />
              <label className={styles.yes}>Yes</label>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionOne(false)
                }}
              />
              <label className={styles.no}>No</label>
              <h1>Does your character focus on alignment?</h1>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionTwo(true)
                }}
              />
              <label className={styles.yes}>Yes</label>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionTwo(false)
                }}
              />
              <label className={styles.no}>No</label>
              <h1>Does your character form relationships?</h1>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionThree(true)
                }}
              />
              <label className={styles.yes}>Yes</label>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionThree(false)
                }}
              />
              <label className={styles.no}>No</label>
              <h1>Does your character have a back story?</h1>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionFour(true)
                }}
              />
              <label className={styles.yes}>Yes</label>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionFour(false)
                }}
              />
              <label className={styles.no}>No</label>
            </form>
          </div>
          <div className={styles.questionThree}>
            <form action="#" method="post" className={styles.pageOne}></form>
          </div>

          <div className={styles.questionFour}>
            <form action="#" method="post" className={styles.pageOne}>
              <button
                className={styles.nextPage}
                onClick={() => {
                  if (
                    questionOne == null ||
                    questionTwo == null ||
                    questionThree == null ||
                    questionFour == null
                  ) {
                    alert('An option or options are missing!')
                  }
                }}
              >
                Next Page
              </button>
            </form>
          </div>
        </div>
      </main>
    </div>
  )
}
