import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from './scroll.module.css'

export default function Home() {
  function choicesMatter() {
    let questionOne = document.querySelector('.questionOne')
    let yes = document.querySelector('.yes')
    let no = document.querySelector('.no')

    if (!yes && !no) {
      alert('An option or options are missing!')
    }
  }

  const [questionOne, setQuestionOne] = useState(false)
  const [questionTwo, setQuestionTwo] = useState(false)
  const [questionThree, setQuestionThree] = useState(false)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div className={styles.content}>
          <div className={styles.questionOne}>
            <form action="#" method="post">
              <h1>Does your Character Use Magic?</h1>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionOne(true)
                }}
              />
              <label className={styles.yes}>Yes</label>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionOne(false)
                }}
              />
              <label className={styles.no}>No</label>
              <h1>Does your character focus on alignment?</h1>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionTwo(true)
                }}
              />
              <label className={styles.yes}>Yes</label>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionTwo(false)
                }}
              />
              <label className={styles.no}>No</label>
              <h1>Does your character form relationships?</h1>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionThree(true)
                }}
              />
              <label className={styles.yes}>Yes</label>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionThree(false)
                }}
              />
              <label className={styles.no}>No</label>
              <h1>Does your character have a back story?</h1>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionFour(true)
                }}
              />
              <label className={styles.yes}>Yes</label>
              <input
                type="radio"
                className={styles.choices}
                onClick={() => {
                  setQuestionFour(false)
                }}
              />
              <label className={styles.no}>No</label>
            </form>
          </div>
          <div className={styles.questionThree}>
            <form action="#" method="post" className={styles.pageOne}></form>
          </div>

          <div className={styles.questionFour}>
            <form action="#" method="post" className={styles.pageOne}>
              <button className={styles.nextPage}>Next Page</button>
            </form>
          </div>
        </div>
      </main>
    </div>
  )
}
